// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoxjyltrvwwbguuawywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveGp5bHRydnd3Ymd1dWF3eXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDY4ODAsImV4cCI6MjA2Nzk4Mjg4MH0.ZVBnigEepBqigSOh68iEfQpPKVfoMYY66Unt6iNz3FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});